"""create incidents table with uuid id

Revision ID: 362229b0e78a
Revises: 
Create Date: 2026-09-15 22:52:14.601305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362229b0e78a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text_hash', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('root_cause_summary', sa.String(length=300), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('priority_reasoning', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('llm_retry_count', sa.Integer(), nullable=False),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_raw_text_hash', 'incidents', ['raw_text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_raw_text_hash', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
