"""native enums for environment and priority, check constraint for category

Revision ID: fbb56f4768b8
Revises: 362229b0e78a
Create Date: 2026-09-15 23:22:52.137457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb56f4768b8'
down_revision: Union[str, Sequence[str], None] = '362229b0e78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

environment_enum = sa.Enum('dev', 'staging', 'prod', name='environment_enum')
priority_enum = sa.Enum('critical', 'high', 'medium', 'low', name='priority_enum')

_category_check_name = 'ck_incidents_category'
_category_values = (
    'database_timeout', 'null_pointer', 'rate_limit_exceeded', 'auth_failure',
    'network_partial_failure', 'validation_error', 'unknown',
)
_category_check_sql = "category IN ({})".format(
    ", ".join(f"'{v}'" for v in _category_values)
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - hand-edited, see below ###
    #
    # autogenerate produced the two alter_column calls but NOT:
    #   (a) creation of the Postgres ENUM types themselves - alter_column
    #       with type_=sa.Enum(...) assumes the type already exists, so
    #       running this against a fresh/existing VARCHAR column fails with
    #       "type environment_enum does not exist" unless created first.
    #   (b) the CHECK constraint for `category` at all - autogenerate only
    #       diffs column *types*, not the CheckConstraint that
    #       native_enum=False/create_constraint=True renders, so this
    #       part had to be added by hand.
    bind = op.get_bind()
    environment_enum.create(bind, checkfirst=True)
    priority_enum.create(bind, checkfirst=True)

    op.alter_column(
        'incidents', 'environment',
        existing_type=sa.VARCHAR(),
        type_=environment_enum,
        existing_nullable=False,
        postgresql_using='environment::environment_enum',
    )
    op.alter_column(
        'incidents', 'priority',
        existing_type=sa.VARCHAR(),
        type_=priority_enum,
        existing_nullable=False,
        postgresql_using='priority::priority_enum',
    )
    op.create_check_constraint(_category_check_name, 'incidents', _category_check_sql)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - hand-edited, see upgrade() ###
    op.drop_constraint(_category_check_name, 'incidents', type_='check')
    op.alter_column(
        'incidents', 'priority',
        existing_type=priority_enum,
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        'incidents', 'environment',
        existing_type=environment_enum,
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )

    bind = op.get_bind()
    priority_enum.drop(bind, checkfirst=True)
    environment_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
